# Generated by Django 3.2.12 on 2022-03-23 20:53

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='adress',
            field=models.CharField(blank=True, max_length=128, verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de naissence'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=45, verbose_name='pays'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='date de modification'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=15, verbose_name='sexe'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='link_gitthub',
            field=models.URLField(blank=True, verbose_name='lien de votre profile gitthub'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='link_linkedin',
            field=models.URLField(blank=True, verbose_name='lien de votre profile linkedin'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='link_mysite',
            field=models.URLField(blank=True, verbose_name='lien de votre de site web'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='link_twitter',
            field=models.URLField(blank=True, verbose_name='lien de votre twitter'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='town',
            field=models.CharField(blank=True, max_length=68, verbose_name='ville'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.CharField(blank=True, max_length=22, verbose_name='code postal'),
        ),
    ]
