# Generated by Django 3.2.12 on 2022-03-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220327_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pseudo',
            field=models.CharField(blank=True, max_length=48, unique=True, verbose_name="non d'utilisateur"),
        ),
    ]
