# Generated by Django 3.2.12 on 2022-03-28 14:29

import apps.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_pseudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img_bg',
            field=models.ImageField(blank=True, default='default/default-img.jpg', null=True, upload_to=apps.profiles.models.rename_img, verbose_name='photo de couverture'),
        ),
    ]
