# Generated by Django 3.2.12 on 2022-03-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20220323_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, max_length=68, verbose_name='région'),
        ),
    ]
