# Generated by Django 3.2.12 on 2022-03-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number_views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Nombre de vue profil'),
        ),
    ]
