# Generated by Django 3.2.12 on 2022-04-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_logout',
            field=models.DateTimeField(blank=True, help_text='last date logout user', null=True, verbose_name='last date logout'),
        ),
    ]
