# Generated by Django 3.2.12 on 2022-04-06 16:38

import apps.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_last_logout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_logout',
        ),
        migrations.AlterField(
            model_name='profile',
            name='img_bg',
            field=models.ImageField(blank=True, default='default/default-img-bg.jpg', null=True, upload_to=apps.profiles.models.rename_img, verbose_name='photo de couverture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img_profile',
            field=models.ImageField(blank=True, default='default/default-img-profile.jpg', null=True, upload_to=apps.profiles.models.rename_img, verbose_name='photo de profile'),
        ),
    ]
