# Generated by Django 3.2.12 on 2022-04-11 13:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_profile_img_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img_bg',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://github.com/Macktireh/linkedin/blob/main/mediafiles/default/default-img-bg.jpg?raw=true', max_length=255, null=True, verbose_name='photo de couverture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img_profile',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://github.com/Macktireh/linkedin/blob/main/mediafiles/default/default-img-profile.jpg?raw=true', max_length=255, null=True, verbose_name='photo de profile'),
        ),
    ]
