# Generated by Django 3.2.12 on 2022-04-12 06:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20220411_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img_bg',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dm68aag3e/image/upload/v1649743327/default-img-bg_zbeoo4.jpg', max_length=255, null=True, verbose_name='photo de couverture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img_profile',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dm68aag3e/image/upload/v1649743168/default-img-profile_hrhx6z.jpg', max_length=255, null=True, verbose_name='photo de profile'),
        ),
    ]
