# Generated by Django 3.2.12 on 2022-03-10 20:56

import apps.post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=apps.post.models.rename_img_video, verbose_name='video'),
        ),
    ]
