# Generated by Django 3.2.12 on 2022-03-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20220312_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='liked',
        ),
        migrations.RemoveField(
            model_name='post',
            name='count_likes',
        ),
    ]
