# Generated by Django 3.2.12 on 2022-03-12 16:40

import apps.post.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_like_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_created',), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=apps.post.models.rename_img_video, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif'])], verbose_name='image'),
        ),
    ]
