# Generated by Django 3.2.12 on 2022-03-17 16:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0007_auto_20220312_1740'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='LikePost',
        ),
    ]
