# Generated by Django 3.2.12 on 2022-03-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reponsecomment',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
