# Generated by Django 3.2.12 on 2022-04-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_last_logout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_logout',
        ),
    ]
