# Generated by Django 3.2.12 on 2022-04-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_last_logout'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_logout',
            field=models.DateTimeField(blank=True, help_text='last date logout user', null=True, verbose_name='last date logout'),
        ),
    ]
