# Generated by Django 3.2.12 on 2022-04-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_auto_20220402_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='date_received',
            new_name='date_receiver',
        ),
    ]
