# Generated by Django 3.2.12 on 2022-04-16 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_rename_date_received_relationship_date_receiver'),
        ('notifications', '0002_alter_notification_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notif_relationship', to='friends.relationship'),
        ),
    ]
