# Generated by Django 3.2.12 on 2022-04-16 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='relationship',
        ),
    ]
